name: typescript-action
description: Template of TypeScript Action

inputs:
  name:
    description: Example
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
