name: ts

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - name: e2e-test
        uses: ./
        with:
          name: foo

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn format
      - uses: int128/update-generated-files-action@68ee6db3259f2fdfb28d29eaefba4fa252b3ed3e # v2
